### ISSUE TITLE
Documentation is wrong?

### ISSUE THREAD

**Issue by abh** [OhMeadhbh/node-mug#1]
The documentation says to use generator.uuid(), but that doesn't work.  Looking in the code it looks like we're supposed to use generator.generate().

**Comment by OhMeadhbh** [comment]
aha. sure enough. lemme double check what's most recently been pushed. i bet i just forgot to add the README.

**Comment by OhMeadhbh** [comment]
okay. finally got a chance to bring the documentation in line with the code. changed references to uuid() to generate() and added docs for Version 3 and 5 UUIDs.

**Comment by abh** [comment]
Thank you!  And thank you for the package.
