### ISSUE TITLE
Document differences between node-mug and node-uuid

### ISSUE THREAD

**Issue by abh** [OhMeadhbh/node-mug#5]
In particular with the new v1.3.x of node-uuid that has v1 and v4 uuids and uses node.js's crypto.\* package I think it'd be helpful for people evaluating uuid generators if you documented how node-mug is different (more randomness, name based uuids, whatever else).

**Comment by OhMeadhbh** [comment]
sounds like a good idea. in my copious free time, i'm probably going to add a few more bells and whistles.. so i'll add a comparison section in the next rev.

**Comment by abh** [comment]
Thanks, because as a consumer of someone else's open source software I WILL DEMAND THEM to spend more of their free time to make it better.

;-)

Just kidding.  Thank you either way!  What's there is great.
